name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev repo
        uses: actions/checkout@v3

      - name: Build App
        run: npm install && npm run build

 
